version: '3.7'
services:
  chatinc-nodered-whatsapp-hessequa-bot:
    image: '429230094765.dkr.ecr.af-south-1.amazonaws.com/chatinc-nodered-whatsapp-hessequa-bot:latest'
    restart: unless-stopped
    networks:
      - PublicNetwork
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.traefik=true"
        - "traefik.http.routers.chatinc-nodered-whatsapp-hessequa-bot.entrypoints=http-internal"
        - "traefik.http.services.chatinc-nodered-whatsapp-hessequa-bot.loadbalancer.server.port=1880"
        - "traefik.http.routers.chatinc-nodered-whatsapp-hessequa-bot.service=chatinc-nodered-whatsapp-hessequa-bot"
        - "traefik.http.routers.chatinc-nodered-whatsapp-hessequa-bot.rule=PathPrefix(`/chatinc-nodered-whatsapp-hessequa-bot`)"
        - "traefik.http.middlewares.chatinc-nodered-whatsapp-hessequa-bot-stripprefix.stripprefix.prefixes=/chatinc-nodered-whatsapp-hessequa-bot"
        - "traefik.http.middlewares.chatinc-nodered-whatsapp-hessequa-bot-stripprefix.stripprefix.forceSlash=false"
        - "traefik.http.routers.chatinc-nodered-whatsapp-hessequa-bot.middlewares=chatinc-nodered-whatsapp-hessequa-bot-stripprefix"
      placement:
        constraints:
          - node.labels.host == app
      resources:
        limits:
          cpus: '0.2'
          memory: 250M
        reservations:
          cpus: '0.2'
          memory: 250M
    logging:
      driver: awslogs
      options:
        awslogs-region: af-south-1
        awslogs-group: chatinc-nodered-whatsapp-hessequa-bot
        awslogs-create-group: 'true'
        tag: '{{.Name}}_{{ with split .ImageName ":" }}{{index . 1}}{{end}}_{{.ID}}'
    environment:
      - CUSTOMER_API_URL=http://core-customer-api:3020
      - CUSTOMER_API_KEY=UL3etRzEwhZmUyJs5TqkFMNj
      - MESSAGES_API_URL=http://core-messages-api:3010
      - MESSAGES_API_KEY=AxUsY4bLXytnG63cgwTGgpWt
      - BOT_ID=1
      - COMPANY_ID=38
      - CHANNEL=WA
      - TIMEZONE=EET
      - NODE_ENV=development
      # logs config
      - "LOGSENE_ENABLED=true"
      - "LOGS_TOKEN=bot-chatinc-nodered-whatsapp-hessequa-bot"

networks:
  PublicNetwork:
    external: true