#!/bin/bash
version="$(jq -r .version package.json)"
previous_version=$(aws ecr describe-images --repository-name $PROJECT --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]'  --output text --region ${AWS_REGION})
if [ "$previous_version" = "latest" ]; then
    previous_version=$(aws ecr describe-images --repository-name $PROJECT --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[1]' --output text --region ${AWS_REGION})
fi
if [ -z "$previous_version" ]; then
    build_number=1
elif [[ "$previous_version" =~ .*"$version".* ]]; then
    previous_build=$(egrep --color=never -o "[0-9]+$" <<< $previous_version) 
    build_number=$((previous_build+1))
else
    build_number=1
fi
build="$version"."$STAGE"."$build_number"
echo $build
